// 命令层汇总出口：各功能模块从这里 re-export，保持历史 import 兼容。
// 业务实现已按功能拆分到 electron/commands/ 目录，本文件只做转发。
export * from './commands/helpers.js'
export * from './commands/audit.js'
export * from './commands/catalog.js'
export * from './commands/products.js'
export * from './commands/inbound.js'
export * from './commands/outbound.js'
export * from './commands/suppliers.js'
export * from './commands/customers.js'
export * from './commands/stocktake.js'
export * from './commands/purchase.js'
export * from './commands/priceTier.js'
export * from './commands/import.js'
export * from './commands/reports.js'
export * from './commands/expenses.js'
export * from './commands/onboarding.js'
export * from './commands/waste.js'
export * from './commands/parts.js'
export * from './commands/kits.js'
export * from './commands/receipt.js'
export * from './commands/aiQuota.js'
export * from './commands/users.js'
export * from './commands/categories.js'
export * from './commands/units.js'
export * from './commands/templates.js'
export * from './commands/clearance.js'
export * from './commands/pricing.js'
// AI 简报（2026-09-15，第一阶段"只算不推"）：把已有口径合成"这周该做什么"。
// 放命令层是为了口径单一 —— 它只调 reports/analytics 的既有口径，不自己发明。
export * from './commands/briefing.js'
