// preload：contextIsolation 下的最小桥接面，channel 白名单防任意调用
const { contextBridge, ipcRenderer } = require('electron')

const CHANNELS = new Set([
  'data:loadAll',
  'product:create',
  'product:update',
  'product:batchUpdate',
  'product:delete',
  'product:mark',
    'product:expiring',
  'category:list',
  'category:listWithCount',
  'category:create',
  'category:rename',
  'category:delete',
  'category:move',
  'unit:list',
  'unit:create',
  'unit:update',
  'unit:delete',
  'unit:move',
  'unit:allowsDecimal',
  'template:list',
  'template:apply',
  'inbound:create',
  'outbound:confirm',
  'outbound:checkout',
  'outbound:return',
  'outbound:exchange',
  'supplier:create',
  'supplier:update',
  'supplier:delete',
  'supplier:pay',
  'supplier:payments',
  'user:list',
  'user:create',
  'user:update',
  'user:delete',
  'user:login',
  'user:logout',
  'user:current',
  'user:staffLoginEnabled',
  'user:setStaffLogin',
  'stocktake:create',
  'stocktake:updateItem',
  'stocktake:complete',
  'stocktake:submit',
  'import:batch',
  'customer:create',
  'customer:update',
  'customer:delete',
  'customer:list',
  'customer:statement',
  'payment:record',
  'expense:create',
  'expense:update',
  'expense:delete',
  'waste:create',
  'waste:list',
  'waste:summary',
  'part:set',
  'part:setMany',
  'part:list',
  'part:all',
  'kit:list',
  'kit:get',
  'kit:save',
  'receipt:register',
  'receipt:list',
  'receipt:reconcile',
  'kit:delete',
  'po:create',
  'po:list',
  'po:detail',
  'po:receive',
  'po:cancel',
  'priceTier:set',
  'priceTier:delete',
  'priceTier:list',
  'backup:now',
  'backup:restore',
  'backup:status',
  'backup:setExtraDir',
  'backup:clearExtraDir',
  'audit:list',
  'supplier:statement',
  'photo:save',
  'photo:delete',
  'payment:getQr',
  'payment:saveQr',
  'payment:deleteQr',
  'ai:status',
  'ai:providers',
  'ai:setProvider',
  'ai:setKey',
  'ai:clearKey',
  'ai:test',
  'ai:dailySummary',
  'ai:chat',
  'ai:parseInboundNote',
  'ai:quota',
  'ai:transcribe',
  'ai:history',
  'ai:insights',
  'knowledge:list',
  'knowledge:save',
  'knowledge:update',
  'knowledge:delete',
  'doubao:status',
  'doubao:setKey',
  'doubao:clearKey',
  'doubao:analyzeImage',
  'doubao:chat',
  'voice:status',
  'voice:transcribe',
  'voice:download',
  'tts:status',
  'tts:speak',
  'tts:download',
  'kws:status',
  'kws:download',
  'kws:push',
  'kws:reset',
  'app:openExternal',
  'app:info',
  'feedback:send',
  'server:status',
  'server:toggle',
  'server:regenerateToken',
  'update:check',
  'update:downloadAndInstall',
  'license:status',
  'license:activate',
  'license:quota',
  'onboarding:status',
  'onboarding:reset',
  'onboarding:finish',
  'cloud:status',
  'cloud:pair',
  'cloud:syncNow',
  'cloud:backupNow',
  'cloud:listBackups',
  'cloud:restore',
  'cloud:regenViewLink',
  'cloud:registerAccount',
  'cloud:loginAccount',
  'cloud:logout',
])

contextBridge.exposeInMainWorld('fi', {
  invoke(channel, payload) {
    if (!CHANNELS.has(channel)) return Promise.reject(new Error(`未知通道: ${channel}`))
    return ipcRenderer.invoke(channel, payload)
  },
  // 订阅模型下载进度（voice:download / tts:download / kws:download 触发），返回取消订阅函数
  onVoiceProgress(callback) {
    const listener = (_e, data) => callback(data)
    ipcRenderer.on('voice:progress', listener)
    return () => ipcRenderer.removeListener('voice:progress', listener)
  },
  onTtsProgress(callback) {
    const listener = (_e, data) => callback(data)
    ipcRenderer.on('tts:progress', listener)
    return () => ipcRenderer.removeListener('tts:progress', listener)
  },
  onKwsProgress(callback) {
    const listener = (_e, data) => callback(data)
    ipcRenderer.on('kws:progress', listener)
    return () => ipcRenderer.removeListener('kws:progress', listener)
  },
})
